name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Add 'checks: write' permission for the test summary action
permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Use the official actions/setup-java action which is the current standard.
      # It also has superior built-in caching for sbt.
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Check format
        run: sbt scalafmtCheckAll

      - name: Compile
        run: CI=true sbt compile

      - name: Run tests
        run: CI=true sbt test

      - name: Publish Test Report
        if: always() # Always run, even if previous steps failed
        uses: test-summary/action@v2
        with:
          paths: "**/target/test-reports/*.xml"
